"""init migrations

Revision ID: 9e4fce8db3a6
Revises: 
Create Date: 2023-03-24 22:25:41.093269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e4fce8db3a6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sitemaps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site", sa.String(length=255), nullable=False),
        sa.Column("loc", sa.String(length=2550), nullable=False),
        sa.Column("lastmod", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sitemaps")
    # ### end Alembic commands ###
